#!/usr/bin/env python3
"""
A minimal Quixote server with static html and static node_modules directory

"""
import os
from os.path import abspath,join

from systemd import journal

from quixote.publish import Publisher
from quixote.directory import Directory, export
from quixote.util import StaticFile,StaticDirectory

BASE_PATH = '/opt/arch32/systemd-socketactivation'

class RootDirectory(Directory):

    _q_exports = [('','index'),('src','app')]

    index = StaticFile(os.path.join(BASE_PATH,'web/index.html'),mime_type="text/html")

    app = StaticDirectory(os.path.join(BASE_PATH,'web/app'))


def create_publisher():
    return Publisher(RootDirectory(),
                     display_exceptions='plain')


if __name__ == '__main__':
    from quixote.server.simple_server import run
    print('creating demo listening on http://localhost:8080/')
    run(create_publisher, host='localhost', port=8080)
